language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: true
before_deploy:
  - openssl aes-256-cbc -K $encrypted_04eb23ffbf70_key -iv $encrypted_04eb23ffbf70_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh-keyscan 137.111.92.23 >> ~/.ssh/known_hosts  # this is remus IP address
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site/ cassidy@remus.science.mq.edu.au:html/
  on:
    branch: master
